FORMAT: 1A
HOST: https://api.ents24.com

# Group Artist
Available resources on the Artist API endpoints.

### List [/artist/list?name={name}&like={like}&genre={genre}&results_per_page={results_per_page}&page={page}&incl_image={incl_image}&image_size={image_size}&full_description={full_description}&incl_also_liked={incl_also_liked}&updated_since={updated_since}&order_by={order_by}&order_direction={order_direction}]
Multiple artist objects with selected fields.  
***NB:*** *You must filter resources retrieved from this end-point with at least one of the following request parameters:*  
`name` `event_name`

#### Artist List [GET]
+ Parameters
  + name (optional, string, `Blondie`) ... The string that matches artist names you want a list of.<br />***NB:*** *Values applied to this parameter may match more than one artist!<br />You should use the `artist/read` end-point to retrieve data for a particular artist.*
  + like (optional, string, `oKkO`) ... Unique identifier string of the artist for which you want a list of similar artists.
  + genre (optional, string, `rock`) ... The genre you want an artists listing for.
  + incl_image (optional, boolean, `1`) ... Decides whether or not an artist image is included in the response.
  + image_size (optional, string, `medium`) ... Chooses the size of image included with each artist object if one is available [`small`, `medium`, `large`].
  + full_description (optional, boolean, `0`) ... Decides whether full or summarised description text is included in the response. 
  + incl_also_liked (optional, boolean, `1`) ... Decides whether or not a list of IDs for similar artists is included in the response.
  + updated_since (optional, datetime, `2015-08-15T15:52:01+00:00`) ... Only retrive artists that have been added/updated since the given timestamp (RFC3339).
  + results_per_page (optional, integer, `25`) ... The number of results you want per page/chunk [`25`, `50`, `75`, `100`].
  + page (optional, string, `ZW0=`) ... The page/chunk of results to be requested.
  + order_by (optional, string, `lastUpdate`) ... Order events by the named object property.
  + order_direction (optional, string, `desc`) ... Ordering direction [`asc`, `desc`].

+ Request

    + Headers

            Authorization: qnFqFAVw8pJMCF1z8tIMYoXwommArRmt9C08jIRA

+ Response 200 (application/json)

    + Headers

            Date: Tue, 26 Aug 2014 08:00:00 GMT
            Expires: Tue, 26 Aug 2014 09:00:00 GMT
            Last-Modified: Tue, 25 Aug 2014 22:10:00 GMT
            X-Next-Page: R2U=
            X-Previous-Page: bUw=
            X-Total-Items-Found: 75

    + Body

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "title": "Artist List",
              "description": "A list of Artist objects with selected fields",
              "type": "array",
              "items": { 
                "type": "object",
                "properties": {
                  "id": {
                    "description": "Unique identifier for the artist",
                    "type": "string"
                  },
                  "name": {
                    "description": "Name of the artist",
                    "type": "string"
                  },
                  "description": {
                    "description": "Description text for the artist",
                    "type": ["string","null"]
                  },
                  "upcomingEvents": {
                    "description": "The number of upcoming events on Ents24 for the artist",
                    "type": "integer"
                  },
                  "image": {
                    "description": "Image asset for the artist",
                    "type": "object",
                    "properties": {
                      "url": {
                        "description": "Image source URL",
                        "type": "string"
                      },
                      "width": {
                        "description": "Image width (px)",
                        "type": "integer"
                      },
                      "height": {
                        "description": "Image height (px)",
                        "type": "integer"
                      },
                      "metadata": {
                        "description": "Metadata related to this image",
                        "type": "object",
                        "properties": {
                          "copyright": {
                            "description": "The copyright holder for this image",
                            "type": ["string","null"]
                          },
                          "caption": {
                            "description": "Caption text for this image",
                            "type": ["string","null"]
                          }
                        }
                      }
                    }
                  },
                  "genre": {
                    "description": "The genre(s) the artist is found under",
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "webLink": {
                    "description": "URL for the web page for the artist on ents24.com",
                    "type": "string"
                  },
                  "fansOnEnts24": {
                    "description": "The number of Ents24 users tracking updates and announcements for this artist",
                    "type": "integer"
                  },
                  "fansAlsoLiked": {
                    "description": "A list of unique identifier strings for artsists similar to this artist",
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "lastUpdate": {
                    "description": "RFC-3339 formatted added/updated timestamp for this object",
                    "type": "string"
                  }
                }
              }
            }

+ Response 204

    + Headers

            Date: Tue, 26 Aug 2014 08:00:00 GMT
            Expires: Tue, 26 Aug 2014 09:00:00 GMT
            Last-Modified: Tue, 25 Aug 2014 22:10:00 GMT
            X-Next-Page: MDg=
            X-Previous-Page: ZW0=
            X-Total-Items-Found: 75

### Read [/artist/read?id={id}&incl_events={incl_events}&incl_image={incl_images}&incl_also_liked={incl_also_liked}&full_description={full_description}]
An artist object with all fields.

#### Artist [GET]
+ Parameters
  + id (required, string, `oKkO`) ... Unique identifier string of the Artist you want full details for.
  + incl_images (optional, boolean, `1`) ... Decides whether or not any artist images are included in the response.  
  + incl_also_liked (optional, boolean, `1`) ... Decides whether or not a list of IDs for similar artists is included in the response.
  + full_description (optional, boolean, `1`) ... Decides whether full or summarised description text is included in the response. 

+ Request

    + Headers

            Authorization: qnFqFAVw8pJMCF1z8tIMYoXwommArRmt9C08jIRA

+ Response 200 (application/json)

    + Headers

            Date: Tue, 26 Aug 2014 08:00:00 GMT
            Expires: Tue, 26 Aug 2014 09:00:00 GMT
            Last-Modified: Tue, 25 Aug 2014 22:10:00 GMT

    + Body

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "title": "Artist",
              "description": "A single Artist object with all fields",
              "type": "object",
              "properties": {
                "id": {
                  "description": "Unique identifier for the artist",
                  "type": "string"
                },
                "name": {
                  "description": "Name of the artist",
                  "type": "string"
                },
                "description": {
                  "description": "Description text for the artist",
                  "type": ["string","null"]
                },
                "upcomingEvents": {
                  "description": "The number of upcoming events on Ents24 for the artist",
                  "type": "integer"
                },
                "images": {
                  "description": "Multiple image assets for the artist",
                  "type": "object",
                  "properties": {
                    "small": {
                      "description": "Small sized image",
                      "type": "object",
                      "properties": {
                        "url": {
                          "description": "Image source URL",
                          "type": "string"
                        },
                        "width": {
                          "description": "Image width (px)",
                          "type": "integer"
                        },
                        "height": {
                          "description": "Image height (px)",
                          "type": "integer"
                        }
                      }
                    },
                    "medium": {
                      "description": "Medium sized image",
                      "type": "object",
                      "properties": {
                        "url": {
                          "description": "Image source URL",
                          "type": "string"
                        },
                        "width": {
                          "description": "Image width (px)",
                          "type": "integer"
                        },
                        "height": {
                          "description": "Image height (px)",
                          "type": "integer"
                        }
                      }
                    },
                    "large": {
                      "description": "Medium sized image",
                      "type": "object",
                      "properties": {
                        "url": {
                          "description": "Image source URL",
                          "type": "string"
                        },
                        "width": {
                          "description": "Image width (px)",
                          "type": "integer"
                        },
                        "height": {
                          "description": "Image height (px)",
                          "type": "integer"
                        }
                      }
                    },
                    "metadata": {
                      "description": "Metadata related to this image",
                      "type": "object",
                      "properties": {
                        "copyright": {
                          "description": "The copyright holder for this image",
                          "type": ["string","null"]
                        },
                        "caption": {
                          "description": "Caption text for this image",
                          "type": ["string","null"]
                        }
                      }
                    }
                  }
                },
                "genre": {
                  "description": "The genre(s) the artist is found under",
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "webLink": {
                  "description": "URL for the web page for the artist on ents24.com",
                  "type": "string"
                },
                "fansOnEnts24": {
                  "description": "The number of Ents24 users tracking updates and announcements for this artist",
                  "type": "integer"
                },
                "fansAlsoLiked": {
                  "description": "A list of unique identifier strings for artsists similar to this artist",
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "lastUpdate": {
                  "description": "RFC-3339 formatted added/updated timestamp for this object",
                  "type": "string"
                }
              }
            }

### Events [/artist/events?id={id}&results_per_page={results_per_page}&page={page}&incl_image={incl_image}&image_size={image_size}&incl_stages={incl_stages}&incl_artists={incl_artists}&incl_occurrences={incl_occurrences}&incl_tickets={incl_tickets}&full_description={full_description}&updated_since={updated_since}&order_by={order_by}&order_direction={order_direction}]
A list of events for an artist.

#### Artist Events [GET]
+ Parameters
  + id (required, string, `oKkO`) ... Unique identifier string of the Artist you want an event listings for.
  + incl_image (optional, boolean, `1`) ... Decides whether or not an event image is included in the response.
  + image_size (optional, string, `medium`) ... Chooses the size of image included with each image object if one is available [`small`, `medium`, `large`].
  + incl_stages (optional, boolean, `1`) ... Decides whether or not a list of stages is included for any festival events in the response. 
  + incl_artists (optional, boolean, `1`) ... Decides whether or not a list of performing artists is included in the response. 
  + incl_occurrences (optional, boolean, `1`) ... Decides whether or not a list of individual event occurrences is included for any repeat events in the response.
  + incl_tickets (optional, boolean, `1`) ... Decides whether or not a list of available tickets is included in the response.  
  + full_description (optional, boolean, `0`) ... Decides whether full or summarised description text is included in the response. 
  + updated_since (optional, datetime, `2015-08-15T15:52:01+00:00`) ... Only retrive events that have been added/updated since the given timestamp (RFC3339).
  + results_per_page (optional, integer, `25`) ... The number of results you want per page/chunk [`25`, `50`, `75`, `100`].
  + page (optional, string, `ZW0=`) ... The page/chunk of results to be requested.
  + order_by (optional, string, `lastUpdate`) ... Order events by the named object property.
  + order_direction (optional, string, `desc`) ... Ordering direction [`asc`, `desc`]. 

+ Request

    + Headers

            Authorization: qnFqFAVw8pJMCF1z8tIMYoXwommArRmt9C08jIRA

+ Response 200 (application/json)

    + Headers

            Date: Tue, 26 Aug 2014 08:00:00 GMT
            Expires: Tue, 26 Aug 2014 09:00:00 GMT
            Last-Modified: Tue, 25 Aug 2014 22:10:00 GMT

    + Body

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "title": "Artist Event List",
              "description": "A list of Event objects with selected fields",
              "type": "array",
              "items": { 
                "type": "object",
                "properties": {
                  "id": {
                    "description": "Unique identifier for the event",
                    "type": "string"
                  },
                  "title": {
                    "description": "Title of the event",
                    "type": ["string","null"]
                  },
                  "headline": {
                    "description": "Headline of the event",
                    "type": ["string","null"]
                  },
                  "startDate": {
                    "description": "RFC-3339 formatted start date for the event",
                    "type": "string"
                  },
                  "endDate": {
                    "description": "RFC-3339 formatted end date for the event",
                    "type": "string"
                  },
                  "startTimeString": {
                    "description": "Start time string for the event",
                    "type": ["string","null"]
                  },
                  "endTimeString": {
                    "description": "End time string for the event",
                    "type": ["string","null"]
                  },
                  "hasMoved": {
                    "description": "Flag to indicate if an event has been moved to another location",
                    "type": "boolean"
                  },
                  "isCancelled": {
                    "description": "Flag to indicate if an event has been cancelled",
                    "type": "boolean"
                  },
                  "isPostponed": {
                    "description": "Flag to indicate if an event has been postponed",
                    "type": "boolean"
                  },
                  "isRescheduled": {
                    "description": "Flag to indicate if an event has been re-scheduled",
                    "type": "boolean"
                  },
                  "isSoldOut": {
                    "description": "Flag to indicate whether the event is sold out",
                    "type": "boolean"
                  },
                  "ticketsAvailable": {
                    "description": "Flag to indicate whether there are tickets available for the event",
                    "type": "boolean"
                  },
                  "isFree": {
                    "description": "Flag to indicate whether the event is free entry",
                    "type": "boolean"
                  },
                  "price": {
                    "description": "Price info for the event",
                    "type": ["string","null"]
                  },
                  "venue": {
                    "description": "Venue the event is being held at",
                    "type": "object",
                    "properties": {
                      "id": {
                        "description": "Unique identifier for the venue",
                        "type": "string"
                      },
                      "name": {
                        "description": "Name of the venue",
                        "type": "string"
                      },
                      "town": {
                        "description": "Town or city where the venue is located",
                        "type": "string"
                      },
                      "location": {
                        "description": "Lat/Lon coordinates of the venue",
                        "$ref": "http://json-schema.org/geo"
                      }
                    }
                  },
                  "description": {
                    "description": "Description text for the event",
                    "type": ["string","null"]
                  },
                  "artists": {
                    "description": "Featured artists",
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "description": "Unique identifier for a featured artist",
                          "type": "string"
                        },
                        "name": {
                          "description": "Name of a featured artist",
                          "type": "string"
                        }
                      }
                    }
                  },
                  "stages": {
                    "description": "Stages at the event",
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "description": "Name of the stage",
                          "type": "string"
                        },
                        "days": {
                          "description": "Days or timespans performances are occuring on the stage",
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "description": "Unique identifier for the stage day(s)",
                                "type": "string"
                              },
                              "startDate": {
                                "description": "The start date for this day or time-span",
                                "type": "string"
                              },
                              "endDate": {
                                "description": "The end date for this day or time-span",
                                "type": "string"
                              },
                              "artists": {
                                "description": "Performing artists",
                                "type": "array",
                                "items": {
                                  "type": "object",
                                  "properties": {
                                    "id": {
                                      "description": "Unique identifier for a featured artist",
                                      "type": "string"
                                    },
                                    "name": {
                                      "description": "Name of a featured artist",
                                      "type": "string"
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "occurrences": {
                    "description": "The individual occurences of a repeated event (E.G. A theatre show)",
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "description": "Unique identifier for the event",
                          "type": "string"
                        },
                        "startDate": {
                          "description": "RFC-3339 formatted start date for the event",
                          "type": "string"
                        },
                        "endDate": {
                          "description": "RFC-3339 formatted end date for the event",
                          "type": "string"
                        },
                        "startTimeString": {
                          "description": "Start time string for the event",
                          "type": ["string","null"]
                        },
                        "endTimeString": {
                          "description": "End time string for the event",
                          "type": ["string","null"]
                        },
                        "hasMoved": {
                          "description": "Flag to indicate if an event has been moved to another location",
                          "type": "boolean"
                        },
                        "isCancelled": {
                          "description": "Flag to indicate if an event has been cancelled",
                          "type": "boolean"
                        },
                        "isPostponed": {
                          "description": "Flag to indicate if an event has been postponed",
                          "type": "boolean"
                        },
                        "isRescheduled": {
                          "description": "Flag to indicate if an event has been re-scheduled",
                          "type": "boolean"
                        },
                        "isSoldOut": {
                          "description": "Flag to indicate whether the event is sold out",
                          "type": "boolean"
                        },
                        "ticketsAvailable": {
                          "description": "Flag to indicate whether there are tickets available for the event",
                          "type": "boolean"
                        },
                        "isFree": {
                          "description": "Flag to indicate whether the event is free entry",
                          "type": "boolean"
                        },
                        "price": {
                          "description": "Price info for the event",
                          "type": ["string","null"]
                        },
                        "tickets": {
                          "description": "Tickets for this event",
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "dateTime": {
                                "description": "RFC-3339 formatted date and time this ticket is valid for",
                                "type": "string"
                              },
                              "supplier": {
                                "description": "The supplier of this ticket",
                                "type": "string"
                              },
                              "price": {
                                "description": "The face-value price for this ticket",
                                "type": ["string","null"]
                              },
                              "totalPrice": {
                                "description": "The total price for this ticket",
                                "type": ["string","null"]
                              },
                              "inclBookingFee": {
                                "description": "Flag indicating whether a booking fee is included in the price of this ticket",
                                "type": "boolean"
                              },
                              "isOnSale": {
                                "description": "Flag indicating whether the ticket is on sale",
                                "type": "boolean"
                              },
                              "isAvailable": {
                                "description": "Flag indicating whether the ticket is available",
                                "type": "boolean"
                              },
                              "isPresaleTicket": {
                                "description": "Flag indicating whether the ticket is a pre-sale ticket",
                                "type": "boolean"
                              },
                              "isResaleTicket": {
                                "description": "Flag indicating whether the ticket is a re-sale ticket",
                                "type": "boolean"
                              },
                              "onSaleFrom": {
                                "description": "RFC-3339 formatted date this ticket goes on sale",
                                "type": ["string","null"]
                              },
                              "onSaleUntil": {
                                "description": "RFC-3339 formatted date this ticket is / will be on sale until",
                                "type": ["string","null"]
                              },
                              "url": {
                                "description": "The purchase URL for this ticket",
                                "type": ["string","null"]
                              },
                              "email": {
                                "description": "The sales email address for this ticket",
                                "type": ["string","null"]
                              },
                              "telephone": {
                                "description": "The sales phone line number for this ticket",
                                "type": ["string","null"]
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "image": {
                    "description": "Image asset for the event",
                    "type": "object",
                    "properties": {
                      "url": {
                        "description": "Image source URL",
                        "type": "string"
                      },
                      "width": {
                        "description": "Image width (px)",
                        "type": "integer"
                      },
                      "height": {
                        "description": "Image height (px)",
                        "type": "integer"
                      },
                      "metadata": {
                        "description": "Metadata related to this image",
                        "type": "object",
                        "properties": {
                          "copyright": {
                            "description": "The copyright holder for this image",
                            "type": ["string","null"]
                          },
                          "caption": {
                            "description": "Caption text for this image",
                            "type": ["string","null"]
                          }
                        }
                      }
                    }
                  },
                  "tickets": {
                    "description": "Tickets for this event",
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "dateTime": {
                          "description": "RFC-3339 formatted date and time this ticket is valid for",
                          "type": "string"
                        },
                        "supplier": {
                          "description": "The supplier of this ticket",
                          "type": "string"
                        },
                        "price": {
                          "description": "The face-value price for this ticket",
                          "type": ["string","null"]
                        },
                        "totalPrice": {
                          "description": "The total price for this ticket",
                          "type": ["string","null"]
                        },
                        "inclBookingFee": {
                          "description": "Flag indicating whether a booking fee is included in the price of this ticket",
                          "type": "boolean"
                        },
                        "isOnSale": {
                          "description": "Flag indicating whether the ticket is on sale",
                          "type": "boolean"
                        },
                        "isAvailable": {
                          "description": "Flag indicating whether the ticket is available",
                          "type": "boolean"
                        },
                        "isPresaleTicket": {
                          "description": "Flag indicating whether the ticket is a pre-sale ticket",
                          "type": "boolean"
                        },
                        "isResaleTicket": {
                          "description": "Flag indicating whether the ticket is a re-sale ticket",
                          "type": "boolean"
                        },
                        "onSaleFrom": {
                          "description": "RFC-3339 formatted date this ticket goes on sale",
                          "type": ["string","null"]
                        },
                        "onSaleUntil": {
                          "description": "RFC-3339 formatted date this ticket is / will be on sale until",
                          "type": ["string","null"]
                        },
                        "url": {
                          "description": "The purchase URL for this ticket",
                          "type": ["string","null"]
                        },
                        "email": {
                          "description": "The sales email address for this ticket",
                          "type": ["string","null"]
                        },
                        "telephone": {
                          "description": "The sales phone line number for this ticket",
                          "type": ["string","null"]
                        }
                      }
                    }
                  },
                  "genre": {
                    "description": "The genre(s) this event is found under",
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "webLink": {
                    "description": "URL for the web page for the event on ents24.com",
                    "type": "string"
                  },
                  "fansOnEnts24": {
                    "description": "The number of Ents24 users tracking updates and announcements for this event",
                    "type": "integer"
                  },
                  "lastUpdate": {
                    "description": "RFC-3339 formatted added/updated timestamp for this object",
                    "type": "string"
                  }
                }
              }
            }

### Image [/artist/image?id={id}&size={size}&format={format}]
An artist image retrieved as either a JSON object or JPEG image.

#### Artist Image [GET]
+ Parameters
  + id (required, string, `oKkO`) ... Unique identifier string of the Artist you want an image for.
  + size (optional, string, `medium`) ... Size of image you want [`small`, `medium`, `large`].
  + format (optional, string, `json`) ... The format of the response you want back from the resource [`json`, `file`].

+ Request

    + Headers

            Authorization: qnFqFAVw8pJMCF1z8tIMYoXwommArRmt9C08jIRA

+ Response 200 (application/json)

    + Headers

            Date: Tue, 26 Aug 2014 08:00:00 GMT
            Expires: Tue, 26 Aug 2014 09:00:00 GMT
            Last-Modified: Tue, 25 Aug 2014 22:10:00 GMT

    + Body

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "title": "Artist Image",
              "description": "An image asset for an artist",
              "type": "object",
              "properties": {
                "url": {
                  "description": "Image source URL",
                  "type": "string"
                },
                "width": {
                  "description": "Image width (px)",
                  "type": "integer"
                },
                "height": {
                  "description": "Image height (px)",
                  "type": "integer"
                },
                "metadata": {
                  "description": "Metadata related to this image",
                  "type": "object",
                  "properties": {
                    "copyright": {
                      "description": "The copyright holder for this image",
                      "type": ["string","null"]
                    },
                    "caption": {
                      "description": "Caption text for this image",
                      "type": ["string","null"]
                    }
                  }
                }
              }
            }

### Widget [/artist/widget?id={id}&encode={encode}]
Return widget data for artist based event listings.

#### Artist Widget [GET]
+ Parameters
  + id (required, string, `oKkO`) ... Unique identifier string of the Artist you want widget data for.
  + encode (optional, string, `utf-8`) ... The character encoding for the data response.

+ Response 200 (application/json)

    + Headers

            Date: Tue, 26 Aug 2014 08:00:00 GMT
            Expires: Tue, 26 Aug 2014 09:00:00 GMT

    + Body
    
            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "title": "Artist Widget",
              "description": "An artist centric event listings widget",
              "type": "object",
              "properties": {
                "jsonLD": {
                  "description": "Schema.org linked-data formatted event listings",
                  "type": ["array", "null"],
                  "items": {
                    "type": "object",
                    "properties": {
                      "@context": {
                        "description": "The context in which the event data is being described (Schema.org)",
                        "type": "string"
                      },
                      "@type": {
                        "description": "The type of event the object represents",
                        "type": "string"
                      },
                      "name": {
                        "description": "The name of the event. This is shown in the rich snippet. See specific policies about event names below",
                        "type": "string"
                      },
                      "url": {
                        "description": "A link to the event's details page",
                        "type": "string"
                      },
                      "startDate": {
                        "description": "The starting date and time of the event (ISO8601)",
                        "type": "string"
                      },
                      "endDate": {
                        "description": "The ending date and time of the event (ISO8601)",
                        "type": "string"
                      },
                      "eventStatus": {
                        "description": "An eventStatus of an event represents its status; particularly useful when an event is cancelled or rescheduled",
                        "type": "string"
                      },
                      "location": {
                        "description": "The location of the event",
                        "type": "object",
                        "properties": {
                          "@type": {
                            "description": "The type of location",
                            "type": "string"
                          },
                          "name": {
                            "description": "The name of the location",
                            "type": "string"
                          },
                          "address": {
                            "description": "Physical/Mailing address of the location",
                            "type": "object",
                            "properties": {
                              "@type": {
                                "description": "The type of address",
                                "type": "string"
                              },
                              "streetAddress": {
                                "description": "The street address",
                                "type": "string"
                              },
                              "addressLocality": {
                                "description": "  The locality. For example, Mountain View.",
                                "type": "string"
                              },
                              "addressRegion": {
                                "description": "The region. For example, CA.",
                                "type": "string"
                              },
                              "postalCode": {
                                "description": "The postal code. For example, 94043.",
                                "type": "string"
                              },
                              "addressCountry": {
                                "description": "The country. For example, USA or ISO 3166-1 alpha-2 country code.",
                                "type": "string"
                              }
                            }
                          },
                          "offers": {
                            "description": " An offer to buy tickets for this event",
                            "type": "array",
                            "items": {
                              "type": "object",
                              "properties": {
                                "@type": {
                                  "description": "The type of offer",
                                  "type": "string"
                                },
                                "category": {
                                  "description": "A category for the offer",
                                  "type": "string"
                                },
                                "price": {
                                  "description": "The offer price of a product",
                                  "type": "string"
                                },
                                "priceCurrency": {
                                  "description": "The currency (in 3-letter ISO 4217 format) of the price",
                                  "type": "string"
                                },
                                "availability": {
                                  "description": "The availability of the offer",
                                  "type": "string"
                                },
                                "validFrom": {
                                  "description": "The date when the offer becomes valid",
                                  "type": "string"
                                },
                                "validThrough": {
                                  "description": "The end of the validity of offer",
                                  "type": "string"
                                },
                                "url": {
                                  "description": "URL of the offer",
                                  "type": "string"
                                }
                              }
                            }
                          },
                          "image" {
                            "description": "The URL for the image for this event",
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "data": {
                  "description": "Artist widget data",
                  "type": "object",
                  "properties": {
                    "name": {
                      "description": "Name of the artist the event listings are for",
                      "type": "string"
                    },
                    "events": {
                      "description": "Event listings for the artist",
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "title": {
                            "description": "Title of event",
                            "type": "string"
                          },
                          "startDate": {
                            "description": "RFC-3339 formatted start date for the event",
                            "type": "string"
                          },
                          "endDate": {
                            "description": "RFC-3339 formatted end date for the event",
                            "type": "string"
                          },
                          "eventUrl": {
                            "description": "URL for event page",
                            "type": "string"
                          },
                          "isFree": {
                            "description": "Flag for if event is free",
                            "type": "boolean"
                          },
                          "status": {
                            "description": "Event status (sold out or not)",
                            "type": "string"
                          },
                          "venueName": {
                            "description": "Name of venue",
                            "type": "string"
                          },
                          "venueTown": {
                            "description": "Name of venue town",
                            "type": "string"
                          },
                          "ticketUrl": {
                            "description": "URL for tickets",
                            "type": "string"
                          },
                          "image": {
                            "description": "Image for event",
                            "type": "string"
                          },
                          "trackUrl": {
                            "description": "URL to track event",
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
