FORMAT: 1A
HOST: https://api.ents24.com

# Group Client Libraries
Ents24 REST API client libraries are available to help you write client applications that access the Ents24 REST API.  

For each language, the client library provides tools and an abstraction layer, letting you construct queries and use response data without having to create HTTP requests or process HTTP responses by hand. Each client library provides classes that correspond to the elements and data types that the API uses.  

### PHP
[Ents24/ents24-api-client](https://github.com/Ents24/ents24-api-client)