FORMAT: 1A
HOST: https://api.ents24.com

# Group Client Authentication
To obtain an access token you must authenticate your client credentials with our authentication server.

### Request Access Token [/auth/token]
Request an access token to authenticate future requests.

#### Auth Token [POST]
+ Parameters
  + client_id (required, string, `aho0bVpKdFURaZ37tkYT`) ... The client ID for the application which requires access to the Ents24 API.
  + client_secret (required, string, `uQmfyQsqeKfIMJg4FKQ9gi8cSLFXATpGFyBx038nHy`) ... The client secret for the application which requires access to the Ents24 API.

+ Request (application/x-www-form-urlencoded)
    
    + Body

            client_id=aho0bVpKdFURaZ37tkYT&client_secret=uQmfyQsqeKfIMJg4FKQ9gi8cSLFXATpGFyBx038nHy

+ Response 200 (application/json)

    + Headers

            Date: Tue, 26 Aug 2014 08:00:00 GMT

    + Body

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "description": "An OAuth2 access token object",
              "type": "object",
              "properties": {
                "access_token": {
                  "description": "The requested access token",
                  "type": "string"
                },
                "token_type": {
                  "description": "The type of access token issued",
                  "type": "string"
                },
                "expires": {
                  "description": "The expiry date of the issued access token",
                  "type": "integer"
                },
                "expires_in": {
                  "description": "The validity timespan for the token from the time of issue",
                  "type": "integer"
                }
              }
            }