FORMAT: 1A
HOST: https://api.ents24.com

# Group Glossary of Terms
**API**  
Application Programming Interfaces enable software to interact with other software through exposed functionality.

**Authentication**  
Identifying the user of the API. Common techniques for authentication include API Keys and OAuth.

**End-point**  
The URI that goes after the base URL and points towards the requested API functionality.

**Expires**  
A header that tells the client it may cache a response until a certain time.

**GET**  
The HTTP method for retrieving resources from a RESTful API.

**Header**  
A header is what's sent before the body of an HTTP request or response.

**HTTP**  
Hypertext Transfer Protocol is how websites and APIs communicate over the internet.

**HTTP Method**  
The part of an HTTP request that tells the server what the client wants to do.

**JSON**  
Javascript Object Notation is a data format commonly used for APIs requests parameters and response body.

**Last-Modified**  
Header which tells client the last time representation changed. Important for conditional If-Modified-Since requests.

**OAuth**  
Open standard authorization framework. Grants access on behalf of an end-user without directly sharing credentials.

**Parameter**  
A parameter is an argument sent to the API which helps define the request and expected response.

**POST**  
The HTTP method for creating resources with a RESTful API.

**Representation**  
Data that describes the state of a resource. Often the body of an HTTP request/response.

**Resource**  
A resource is some object or entitity that has a URI where it can be manuiplulated through HTTP requests.

**REST**  
Representational state transfer is an architectural pattern for interacting with resources via HTTP methods.

**Request**  
An API Request is what's being sent to the API's base url and endpoint including headers and parameters.

**Response**  
The Response is what the API sends back after a request, including the headers and body.

**Server**  
The server is software or hardware that provides a service by responding to requests across a network.

**SSL**  
A cryptographic protocol that secures traffic on the internet.

**Status Code**  
HTTP status codes are what the server sends back to the client with the response in regards to the status of the request.

**URI**  
Unique Resource Identifier