FORMAT: 1A
HOST: https://api.ents24.com

# Group Request Authentication
Your access token must be included as an **Authorization header** in each request sent to the API.

    Authorization: qnFqFAVw8pJMCF1z8tIMYoXwommArRmt9C08jIRA

Tokens are valid for 60 days (5184000 seconds) from the time they are issued. Once a token has expired you will need the request a new one from the authentication server in order to continue to make requests to the API.