FORMAT: 1A
HOST: https://api.ents24.com

# Group Testing Requests
We reccomend testing your requests with a HTTP client before using them in program code. If you live in the command-line then cURL is your friend. If you prefer a GUI on other-hand we recommend using **Postman**. If you're new to APIs you can find a collection of example API requests in our documentation repository on **GitHub**. 

### cURL Example
    curl -X GET -H "Authorization:qnFqFAVw8pJMCF1z8tIMYoXwommArRmt9C08jIRA" -H "Cache-Control:no-cache" https://api.ents24.com/event/list?location=Bristol&date=2014-08-29

### Postman
+ [Download Postman HTTP Client](http://www.getpostman.com/)
+ [Example request collection](https://github.com/Ents24/public-api-docs)