FORMAT: 1A
HOST: https://api.ents24.com

# Group User Authentication
To obtain an access token you must authenticate your client user credentials with our authentication server.
User credentials should represent a valid Ents24 user account. 

### Request Access Token [/auth/login]
Request an access token to authenticate future client user requests.

#### Auth Login [POST]
+ Parameters
  + client_id (required, string, `aho0bVpKdFURaZ37tkYT`) ... The client ID for the application which requires access to the Ents24 API.
  + client_secret (required, string, `uQmfyQsqeKfIMJg4FKQ9gi8cSLFXATpGFyBx038nHy`) ... The client secret for the application which requires access to the Ents24 API.
  + username (required, string, `name@example.com`) ... The registered email address used to login to Ents24.
  + password (required, string, `QyrkQZLLOgpeEj`) ... The registered password used to login to Ents24.

+ Request (application/x-www-form-urlencoded)
    
    + Body

            client_id=aho0bVpKdFURaZ37tkYT&client_secret=uQmfyQsqeKfIMJg4FKQ9gi8cSLFXATpGFyBx038nHy&username=auser&password=mypa55w0rd

+ Response 200 (application/json)

    + Headers

            Date: Tue, 26 Aug 2014 08:00:00 GMT

    + Body

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "description": "An OAuth2 access token object",
              "type": "object",
              "properties": {
                "access_token": {
                  "description": "The requested access token",
                  "type": "string"
                },
                "token_type": {
                  "description": "The type of access token issued",
                  "type": "string"
                },
                "expires": {
                  "description": "The expiry date of the issued access token",
                  "type": "integer"
                },
                "expires_in": {
                  "description": "The validity timespan for the token from the time of issue",
                  "type": "integer"
                }
              }
            }